# theme: jekyll-theme-cayman

# Site settings
title: Vansiit's Blog
SEOTitle: vansiit的博客 | vansiit Blog
header-img: img/bg/output.jpg
email: vansiit@163.com
description: "开发 | vansiit，Web & Front-end Engineer | vansiit的个人博客呀"
keyword: "vansiit, Java, vansiit Blog, 博客, Blog, Css, 数据库, 全栈"
url: "https://zlvansiit.github.io/"              # your host, for absolute URL
baseurl: ""                       # for example, '/blog' if your blog hosted on 'host/blog'

pages: [
  {
    "url": "",
    "title": ""
  }
]


# avatar and Favicon
favicon: /img/favicon.ico


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "坐睡觉来无一事，满窗晴日看蚕生"
sidebar-avatar: /img/bg/output6.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# SNS settings
RSS: true
weibo_username:     false
zhihu_username:     false
github_username:    ZLVansiit


# Build settings
paginate: 10
plugins: [jekyll-paginate]
# gems: [jekyll-paginate]


# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: ce8fe1a6dd8dfa4d4814                            #生成的clientID
  clientSecret: 5fde20930cab3816338e352eb84ead8f824012a8    #生成的clientSecret
  repo: zlvansiit.github.io    #仓库名称
  owner: zlvansiit    #github用户名
  admin: zlvansiit
  # distractionFreeMode: true #是否启用类似FB的阴影遮罩


# Friends
friends: [
  {
    title: "zlvansiit's github ",
    href: "https://zlvansiit.github.io/"
  }
]

